import Navbar from "@/src/components/Navbar";
import type { Metadata } from "next";
import 'easymde/dist/easymde.min.css';
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar/>
      <main>
        {children}
        <Toaster />
      </main>
      
    </>
  );
}
