import type { Metadata } from "next";
import "./globals.css";
import { Mulish } from 'next/font/google';
import { ThemeProvider } from "../components/ThemeProvider";
import { HawkProvider } from "../components/HawkProvider";

const mulish = Mulish({
    subsets: ['latin', 'cyrillic'], // Укажите нужные подмножества
    variable: '--font-mulish', // Определите CSS переменную для использования
  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${mulish.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <HawkProvider>
              {children}
            </HawkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
